[2025-03-11T17:45:10.481+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_bronze_and_silver_layer.transform_silver_5mins_incremental scheduled__2025-03-11T17:40:00+00:00 [queued]>
[2025-03-11T17:45:10.486+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_bronze_and_silver_layer.transform_silver_5mins_incremental scheduled__2025-03-11T17:40:00+00:00 [queued]>
[2025-03-11T17:45:10.486+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-03-11T17:45:10.496+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): transform_silver_5mins_incremental> on 2025-03-11 17:40:00+00:00
[2025-03-11T17:45:10.501+0000] {standard_task_runner.py:57} INFO - Started process 4604 to run task
[2025-03-11T17:45:10.504+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'process_bronze_and_silver_layer', 'transform_silver_5mins_incremental', 'scheduled__2025-03-11T17:40:00+00:00', '--job-id', '788', '--raw', '--subdir', 'DAGS_FOLDER/5mins_processing_pipeline.py', '--cfg-path', '/tmp/tmp4rez8efe']
[2025-03-11T17:45:10.609+0000] {standard_task_runner.py:85} INFO - Job 788: Subtask transform_silver_5mins_incremental
[2025-03-11T17:45:10.632+0000] {task_command.py:416} INFO - Running <TaskInstance: process_bronze_and_silver_layer.transform_silver_5mins_incremental scheduled__2025-03-11T17:40:00+00:00 [running]> on host c8e526380ef3
[2025-03-11T17:45:10.666+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Andrew Tran' AIRFLOW_CTX_DAG_ID='process_bronze_and_silver_layer' AIRFLOW_CTX_TASK_ID='transform_silver_5mins_incremental' AIRFLOW_CTX_EXECUTION_DATE='2025-03-11T17:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-11T17:40:00+00:00'
[2025-03-11T17:45:10.667+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-03-11T17:45:10.667+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /opt/***/dbt/playstudio_project && export WAREHOUSE_HOST=None && export WAREHOUSE_PASSWORD=None && export WAREHOUSE_USER=None && dbt run --select tag:silver_5mins_incremental --target prod']
[2025-03-11T17:45:10.679+0000] {subprocess.py:86} INFO - Output:
[2025-03-11T17:45:14.241+0000] {subprocess.py:93} INFO - [0m17:45:14  Running with dbt=1.7.18
[2025-03-11T17:45:14.418+0000] {subprocess.py:93} INFO - [0m17:45:14  Registered adapter: postgres=1.7.18
[2025-03-11T17:45:14.440+0000] {subprocess.py:93} INFO - [0m17:45:14  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2025-03-11T17:45:14.440+0000] {subprocess.py:93} INFO - There are 1 unused configuration paths:
[2025-03-11T17:45:14.440+0000] {subprocess.py:93} INFO - - models.playstudio_project.example
[2025-03-11T17:45:14.453+0000] {subprocess.py:93} INFO - [0m17:45:14  Found 2 models, 2 sources, 0 exposures, 0 metrics, 401 macros, 0 groups, 0 semantic models
[2025-03-11T17:45:14.455+0000] {subprocess.py:93} INFO - [0m17:45:14
[2025-03-11T17:45:14.530+0000] {subprocess.py:93} INFO - [0m17:45:14  Concurrency: 1 threads (target='prod')
[2025-03-11T17:45:14.532+0000] {subprocess.py:93} INFO - [0m17:45:14
[2025-03-11T17:45:14.539+0000] {subprocess.py:93} INFO - [0m17:45:14  1 of 2 START sql incremental model silver_layer.silver_purchases ............... [RUN]
[2025-03-11T17:45:14.677+0000] {subprocess.py:93} INFO - [0m17:45:14  1 of 2 OK created sql incremental model silver_layer.silver_purchases .......... [[32mINSERT 0 36[0m in 0.14s]
[2025-03-11T17:45:14.681+0000] {subprocess.py:93} INFO - [0m17:45:14  2 of 2 START sql incremental model silver_layer.silver_spins_hourly ............ [RUN]
[2025-03-11T17:45:14.698+0000] {subprocess.py:93} INFO - [0m17:45:14  2 of 2 ERROR creating sql incremental model silver_layer.silver_spins_hourly ... [[31mERROR[0m in 0.02s]
[2025-03-11T17:45:14.705+0000] {subprocess.py:93} INFO - [0m17:45:14
[2025-03-11T17:45:14.705+0000] {subprocess.py:93} INFO - [0m17:45:14  Finished running 2 incremental models in 0 hours 0 minutes and 0.25 seconds (0.25s).
[2025-03-11T17:45:14.720+0000] {subprocess.py:93} INFO - [0m17:45:14
[2025-03-11T17:45:14.720+0000] {subprocess.py:93} INFO - [0m17:45:14  [31mCompleted with 1 error and 0 warnings:[0m
[2025-03-11T17:45:14.721+0000] {subprocess.py:93} INFO - [0m17:45:14
[2025-03-11T17:45:14.721+0000] {subprocess.py:93} INFO - [0m17:45:14    Database Error in model silver_spins_hourly (models/silver_layer/silver_spins_hourly.sql)
[2025-03-11T17:45:14.721+0000] {subprocess.py:93} INFO -   column "transaction_id" does not exist
[2025-03-11T17:45:14.721+0000] {subprocess.py:93} INFO -   LINE 20:         CAST(transaction_id AS TEXT) AS transaction_id,
[2025-03-11T17:45:14.722+0000] {subprocess.py:93} INFO -                         ^
[2025-03-11T17:45:14.722+0000] {subprocess.py:93} INFO -   compiled Code at target/run/playstudio_project/models/silver_layer/silver_spins_hourly.sql
[2025-03-11T17:45:14.722+0000] {subprocess.py:93} INFO - [0m17:45:14
[2025-03-11T17:45:14.726+0000] {subprocess.py:93} INFO - [0m17:45:14  Done. PASS=1 WARN=0 ERROR=1 SKIP=0 TOTAL=2
[2025-03-11T17:45:16.061+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-03-11T17:45:16.078+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-11T17:45:16.081+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=process_bronze_and_silver_layer, task_id=transform_silver_5mins_incremental, execution_date=20250311T174000, start_date=20250311T174510, end_date=20250311T174516
[2025-03-11T17:45:16.103+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 788 for task transform_silver_5mins_incremental (Bash command failed. The command returned a non-zero exit code 1.; 4604)
[2025-03-11T17:45:16.131+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-03-11T17:45:16.140+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
