[2025-03-12T16:25:32.503+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hourly_processing_pipeline.aggregate_final_table_incremental manual__2025-03-12T16:25:22.449550+00:00 [queued]>
[2025-03-12T16:25:32.509+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hourly_processing_pipeline.aggregate_final_table_incremental manual__2025-03-12T16:25:22.449550+00:00 [queued]>
[2025-03-12T16:25:32.509+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-03-12T16:25:32.517+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): aggregate_final_table_incremental> on 2025-03-12 16:25:22.449550+00:00
[2025-03-12T16:25:32.520+0000] {standard_task_runner.py:57} INFO - Started process 42766 to run task
[2025-03-12T16:25:32.523+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'hourly_processing_pipeline', 'aggregate_final_table_incremental', 'manual__2025-03-12T16:25:22.449550+00:00', '--job-id', '3225', '--raw', '--subdir', 'DAGS_FOLDER/hourly_processing_pipeline.py', '--cfg-path', '/tmp/tmp9aqoo63v']
[2025-03-12T16:25:32.525+0000] {standard_task_runner.py:85} INFO - Job 3225: Subtask aggregate_final_table_incremental
[2025-03-12T16:25:32.697+0000] {task_command.py:416} INFO - Running <TaskInstance: hourly_processing_pipeline.aggregate_final_table_incremental manual__2025-03-12T16:25:22.449550+00:00 [running]> on host c8e526380ef3
[2025-03-12T16:25:32.733+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Andrew Tran' AIRFLOW_CTX_DAG_ID='hourly_processing_pipeline' AIRFLOW_CTX_TASK_ID='aggregate_final_table_incremental' AIRFLOW_CTX_EXECUTION_DATE='2025-03-12T16:25:22.449550+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-12T16:25:22.449550+00:00'
[2025-03-12T16:25:32.734+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-03-12T16:25:32.734+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /opt/***/dbt/playstudio_project && export WAREHOUSE_HOST=None && export WAREHOUSE_PASSWORD=None && export WAREHOUSE_USER=None && dbt run --select tag:gold_layer --target prod']
[2025-03-12T16:25:32.741+0000] {subprocess.py:86} INFO - Output:
[2025-03-12T16:25:34.007+0000] {subprocess.py:93} INFO - [0m16:25:34  Running with dbt=1.7.18
[2025-03-12T16:25:34.109+0000] {subprocess.py:93} INFO - [0m16:25:34  Registered adapter: postgres=1.7.18
[2025-03-12T16:25:34.127+0000] {subprocess.py:93} INFO - [0m16:25:34  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2025-03-12T16:25:34.127+0000] {subprocess.py:93} INFO - There are 1 unused configuration paths:
[2025-03-12T16:25:34.127+0000] {subprocess.py:93} INFO - - models.playstudio_project.bronze_layer
[2025-03-12T16:25:34.137+0000] {subprocess.py:93} INFO - [0m16:25:34  Found 3 models, 2 sources, 0 exposures, 0 metrics, 402 macros, 0 groups, 0 semantic models
[2025-03-12T16:25:34.139+0000] {subprocess.py:93} INFO - [0m16:25:34
[2025-03-12T16:25:34.198+0000] {subprocess.py:93} INFO - [0m16:25:34  Concurrency: 1 threads (target='prod')
[2025-03-12T16:25:34.199+0000] {subprocess.py:93} INFO - [0m16:25:34
[2025-03-12T16:25:34.203+0000] {subprocess.py:93} INFO - [0m16:25:34  1 of 1 START sql incremental model gold_layer.aggregated_final_table ........... [RUN]
[2025-03-12T16:25:34.240+0000] {subprocess.py:93} INFO - [0m16:25:34  1 of 1 ERROR creating sql incremental model gold_layer.aggregated_final_table .. [[31mERROR[0m in 0.04s]
[2025-03-12T16:25:34.245+0000] {subprocess.py:93} INFO - [0m16:25:34
[2025-03-12T16:25:34.245+0000] {subprocess.py:93} INFO - [0m16:25:34  Finished running 1 incremental model in 0 hours 0 minutes and 0.11 seconds (0.11s).
[2025-03-12T16:25:34.251+0000] {subprocess.py:93} INFO - [0m16:25:34
[2025-03-12T16:25:34.251+0000] {subprocess.py:93} INFO - [0m16:25:34  [31mCompleted with 1 error and 0 warnings:[0m
[2025-03-12T16:25:34.251+0000] {subprocess.py:93} INFO - [0m16:25:34
[2025-03-12T16:25:34.251+0000] {subprocess.py:93} INFO - [0m16:25:34    Database Error in model aggregated_final_table (models/gold_layer/aggregated_final_table.sql)
[2025-03-12T16:25:34.251+0000] {subprocess.py:93} INFO -   syntax error at or near "FROM"
[2025-03-12T16:25:34.251+0000] {subprocess.py:93} INFO -   LINE 24:     FROM "warehouse_db"."silver_layer"."silver_purchases"
[2025-03-12T16:25:34.251+0000] {subprocess.py:93} INFO -                ^
[2025-03-12T16:25:34.251+0000] {subprocess.py:93} INFO - [0m16:25:34
[2025-03-12T16:25:34.252+0000] {subprocess.py:93} INFO - [0m16:25:34  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
[2025-03-12T16:25:36.098+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-03-12T16:25:36.109+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-12T16:25:36.111+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=hourly_processing_pipeline, task_id=aggregate_final_table_incremental, execution_date=20250312T162522, start_date=20250312T162532, end_date=20250312T162536
[2025-03-12T16:25:36.121+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 3225 for task aggregate_final_table_incremental (Bash command failed. The command returned a non-zero exit code 1.; 42766)
[2025-03-12T16:25:36.133+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-03-12T16:25:36.230+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
