[2025-03-12T16:30:24.706+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hourly_processing_pipeline.aggregate_final_table_incremental manual__2025-03-12T16:30:13.782654+00:00 [queued]>
[2025-03-12T16:30:24.709+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hourly_processing_pipeline.aggregate_final_table_incremental manual__2025-03-12T16:30:13.782654+00:00 [queued]>
[2025-03-12T16:30:24.709+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-03-12T16:30:24.715+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): aggregate_final_table_incremental> on 2025-03-12 16:30:13.782654+00:00
[2025-03-12T16:30:24.718+0000] {standard_task_runner.py:57} INFO - Started process 43015 to run task
[2025-03-12T16:30:24.720+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'hourly_processing_pipeline', 'aggregate_final_table_incremental', 'manual__2025-03-12T16:30:13.782654+00:00', '--job-id', '3239', '--raw', '--subdir', 'DAGS_FOLDER/hourly_processing_pipeline.py', '--cfg-path', '/tmp/tmpsg95ktit']
[2025-03-12T16:30:24.721+0000] {standard_task_runner.py:85} INFO - Job 3239: Subtask aggregate_final_table_incremental
[2025-03-12T16:30:24.823+0000] {task_command.py:416} INFO - Running <TaskInstance: hourly_processing_pipeline.aggregate_final_table_incremental manual__2025-03-12T16:30:13.782654+00:00 [running]> on host c8e526380ef3
[2025-03-12T16:30:24.852+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Andrew Tran' AIRFLOW_CTX_DAG_ID='hourly_processing_pipeline' AIRFLOW_CTX_TASK_ID='aggregate_final_table_incremental' AIRFLOW_CTX_EXECUTION_DATE='2025-03-12T16:30:13.782654+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-12T16:30:13.782654+00:00'
[2025-03-12T16:30:24.853+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-03-12T16:30:24.853+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /opt/***/dbt/playstudio_project && export WAREHOUSE_HOST=None && export WAREHOUSE_PASSWORD=None && export WAREHOUSE_USER=None && dbt run --select tag:gold_layer --target prod']
[2025-03-12T16:30:24.859+0000] {subprocess.py:86} INFO - Output:
[2025-03-12T16:30:26.170+0000] {subprocess.py:93} INFO - [0m16:30:26  Running with dbt=1.7.18
[2025-03-12T16:30:26.267+0000] {subprocess.py:93} INFO - [0m16:30:26  Registered adapter: postgres=1.7.18
[2025-03-12T16:30:26.285+0000] {subprocess.py:93} INFO - [0m16:30:26  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2025-03-12T16:30:26.285+0000] {subprocess.py:93} INFO - There are 1 unused configuration paths:
[2025-03-12T16:30:26.285+0000] {subprocess.py:93} INFO - - models.playstudio_project.bronze_layer
[2025-03-12T16:30:26.295+0000] {subprocess.py:93} INFO - [0m16:30:26  Found 3 models, 2 sources, 0 exposures, 0 metrics, 402 macros, 0 groups, 0 semantic models
[2025-03-12T16:30:26.295+0000] {subprocess.py:93} INFO - [0m16:30:26
[2025-03-12T16:30:26.355+0000] {subprocess.py:93} INFO - [0m16:30:26  Concurrency: 1 threads (target='prod')
[2025-03-12T16:30:26.356+0000] {subprocess.py:93} INFO - [0m16:30:26
[2025-03-12T16:30:26.362+0000] {subprocess.py:93} INFO - [0m16:30:26  1 of 1 START sql incremental model gold_layer.aggregated_final_table ........... [RUN]
[2025-03-12T16:30:26.403+0000] {subprocess.py:93} INFO - [0m16:30:26  1 of 1 ERROR creating sql incremental model gold_layer.aggregated_final_table .. [[31mERROR[0m in 0.04s]
[2025-03-12T16:30:26.409+0000] {subprocess.py:93} INFO - [0m16:30:26
[2025-03-12T16:30:26.409+0000] {subprocess.py:93} INFO - [0m16:30:26  Finished running 1 incremental model in 0 hours 0 minutes and 0.11 seconds (0.11s).
[2025-03-12T16:30:26.414+0000] {subprocess.py:93} INFO - [0m16:30:26
[2025-03-12T16:30:26.416+0000] {subprocess.py:93} INFO - [0m16:30:26  [31mCompleted with 1 error and 0 warnings:[0m
[2025-03-12T16:30:26.416+0000] {subprocess.py:93} INFO - [0m16:30:26
[2025-03-12T16:30:26.416+0000] {subprocess.py:93} INFO - [0m16:30:26    Database Error in model aggregated_final_table (models/gold_layer/aggregated_final_table.sql)
[2025-03-12T16:30:26.416+0000] {subprocess.py:93} INFO -   column aph.country does not exist
[2025-03-12T16:30:26.416+0000] {subprocess.py:93} INFO -   LINE 40:         aph.country,
[2025-03-12T16:30:26.416+0000] {subprocess.py:93} INFO -                    ^
[2025-03-12T16:30:26.416+0000] {subprocess.py:93} INFO -   HINT:  Perhaps you meant to reference the column "ash.country".
[2025-03-12T16:30:26.416+0000] {subprocess.py:93} INFO - [0m16:30:26
[2025-03-12T16:30:26.416+0000] {subprocess.py:93} INFO - [0m16:30:26  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1
[2025-03-12T16:30:27.715+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-03-12T16:30:27.722+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-12T16:30:27.724+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=hourly_processing_pipeline, task_id=aggregate_final_table_incremental, execution_date=20250312T163013, start_date=20250312T163024, end_date=20250312T163027
[2025-03-12T16:30:27.733+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 3239 for task aggregate_final_table_incremental (Bash command failed. The command returned a non-zero exit code 1.; 43015)
[2025-03-12T16:30:27.764+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-03-12T16:30:27.889+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
