[2025-03-14T02:58:19.411+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: five_mins_processing_pipeline.branch_hourly_pipeline scheduled__2025-03-14T02:50:00+00:00 [queued]>
[2025-03-14T02:58:19.414+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: five_mins_processing_pipeline.branch_hourly_pipeline scheduled__2025-03-14T02:50:00+00:00 [queued]>
[2025-03-14T02:58:19.414+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-03-14T02:58:19.422+0000] {taskinstance.py:1382} INFO - Executing <Task(BranchPythonOperator): branch_hourly_pipeline> on 2025-03-14 02:50:00+00:00
[2025-03-14T02:58:19.424+0000] {standard_task_runner.py:57} INFO - Started process 78403 to run task
[2025-03-14T02:58:19.426+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'five_mins_processing_pipeline', 'branch_hourly_pipeline', 'scheduled__2025-03-14T02:50:00+00:00', '--job-id', '3737', '--raw', '--subdir', 'DAGS_FOLDER/five_mins_processing_pipeline.py', '--cfg-path', '/tmp/tmpkof5qjlu']
[2025-03-14T02:58:19.428+0000] {standard_task_runner.py:85} INFO - Job 3737: Subtask branch_hourly_pipeline
[2025-03-14T02:58:19.453+0000] {task_command.py:416} INFO - Running <TaskInstance: five_mins_processing_pipeline.branch_hourly_pipeline scheduled__2025-03-14T02:50:00+00:00 [running]> on host c8e526380ef3
[2025-03-14T02:58:19.499+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Andrew Tran' AIRFLOW_CTX_DAG_ID='five_mins_processing_pipeline' AIRFLOW_CTX_TASK_ID='branch_hourly_pipeline' AIRFLOW_CTX_EXECUTION_DATE='2025-03-14T02:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-14T02:50:00+00:00'
[2025-03-14T02:58:19.513+0000] {pipeline_utils.py:231} ERROR - Error checking if DAG hourly_processing_pipeline is running: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
[2025-03-14T02:58:19.514+0000] {five_mins_processing_pipeline.py:290} INFO - Hourly data needs refresh and DAG is not running - triggering hourly pipeline
[2025-03-14T02:58:19.514+0000] {python.py:194} INFO - Done. Returned value was: trigger_hourly_pipeline
[2025-03-14T02:58:19.514+0000] {python.py:227} INFO - Branch callable return trigger_hourly_pipeline
[2025-03-14T02:58:19.514+0000] {skipmixin.py:173} INFO - Following branch trigger_hourly_pipeline
[2025-03-14T02:58:19.520+0000] {skipmixin.py:239} INFO - Skipping tasks []
[2025-03-14T02:58:19.537+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=five_mins_processing_pipeline, task_id=branch_hourly_pipeline, execution_date=20250314T025000, start_date=20250314T025819, end_date=20250314T025819
[2025-03-14T02:58:19.573+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-03-14T02:58:19.588+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
