[2025-03-11T14:43:39.717+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_bronze_layer_dag.prepare_dag_execution manual__2025-03-11T14:43:35+00:00 [queued]>
[2025-03-11T14:43:39.721+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_bronze_layer_dag.prepare_dag_execution manual__2025-03-11T14:43:35+00:00 [queued]>
[2025-03-11T14:43:39.721+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-03-11T14:43:39.728+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): prepare_dag_execution> on 2025-03-11 14:43:35+00:00
[2025-03-11T14:43:39.731+0000] {standard_task_runner.py:57} INFO - Started process 16891 to run task
[2025-03-11T14:43:39.734+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ingest_bronze_layer_dag', 'prepare_dag_execution', 'manual__2025-03-11T14:43:35+00:00', '--job-id', '453', '--raw', '--subdir', 'DAGS_FOLDER/ingesting_pipeline.py', '--cfg-path', '/tmp/tmpy0d83pam']
[2025-03-11T14:43:39.736+0000] {standard_task_runner.py:85} INFO - Job 453: Subtask prepare_dag_execution
[2025-03-11T14:43:39.772+0000] {task_command.py:416} INFO - Running <TaskInstance: ingest_bronze_layer_dag.prepare_dag_execution manual__2025-03-11T14:43:35+00:00 [running]> on host 41ccd9d1769c
[2025-03-11T14:43:40.087+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Andrew Tran' AIRFLOW_CTX_DAG_ID='ingest_bronze_layer_dag' AIRFLOW_CTX_TASK_ID='prepare_dag_execution' AIRFLOW_CTX_EXECUTION_DATE='2025-03-11T14:43:35+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-11T14:43:35+00:00'
[2025-03-11T14:43:40.095+0000] {base.py:73} INFO - Using connection ID 'postgres_warehouse_db' for task execution.
[2025-03-11T14:43:40.100+0000] {warnings.py:109} WARNING - /opt/***/dags/ingesting_pipeline.py:136: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

[2025-03-11T14:43:40.103+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ingesting_pipeline.py", line 245, in prepare_dag_execution
    incremental_time = get_latest_updated_at_from_table(warehouse_hook, table_name=DB_CONFIG["silver"]["tables"]["purchases"], schema_name=DB_CONFIG["silver"]["schema"])
  File "/opt/airflow/dags/ingesting_pipeline.py", line 149, in get_latest_updated_at_from_table
    latest_updated_at = df.iloc[0]['max'].strftime("%Y-%m-%d %H:%M:%S")
AttributeError: 'NoneType' object has no attribute 'strftime'
[2025-03-11T14:43:40.106+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=ingest_bronze_layer_dag, task_id=prepare_dag_execution, execution_date=20250311T144335, start_date=20250311T144339, end_date=20250311T144340
[2025-03-11T14:43:40.111+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 453 for task prepare_dag_execution ('NoneType' object has no attribute 'strftime'; 16891)
[2025-03-11T14:43:40.138+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-03-11T14:43:40.231+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
